### ISSUE TITLE
TODO: Remove unsafe and development-unfriendly `_G`

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#101]
`_G` metatable can be detected in some executors, and even if it can't, it's still not a direct replacement to locals or globals since you still have to explicitly specify that the object is in `_G`. most executors have `getgenv()` now, which is both safe to use and a drop-in-replacement for global objects, meaning ambiguous syntax but higher priority for the global environment.

**Comment by Toon-arch** [comment]
we should probably use `shared`. it's not detectable like `_G`, acts the same as `getgenv()`, but it's supported on every single executor

**Comment by W1nterBr33ze** [comment]
thought `shared` was exactly the same as `_G`

**Comment by KaizerFox** [comment]
:trollface:
