### ISSUE TITLE
TODO: Start using modular components with `rbxm-suite`

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#113]
using modules and [`rbxm-suite`](https://github.com/richie0866/rbxm-suite) is a far cleaner and modern approach to a single file where you have to use the `find` feature in editors or browsers to search for a certain piece of code. having a compiled `rbxm` (Roblox model) file allows easier debugging and promotes good code habits. additionally, it allows usage of [Rojo's](https://github.com/rojo-rbx/rojo) workflow tools and [`roblox-ts`](https://github.com/roblox-ts/roblox-ts) to build better code.

**Comment by W1nterBr33ze** [comment]
do not.

**Comment by Epikest** [comment]
?

**Comment by W1nterBr33ze** [comment]
we are **not** using `rbxm-suite`
