### ISSUE TITLE
Infinite Store doesn't support Arceus X

### ISSUE THREAD

**Issue by vbedesu** [Infinite-Store/Infinite-Store#116]
### Expected behavior

The script to work.

### Actual behavior

it doesn't run on arceus x, thefore it needs further development.

### Steps to reproduce

run the script on arceus x

### Infinite Store version

v0.0.0

### Checks

- [X] I am __not__ using a mobile device.
- [X] I am __not__ using an outdated version of Infinite Store.
- [X] I asked in [Infinite Store's Discord server](https://discord.com/invite/dubhsUGcZe) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Implement support for Arceus X. :trollface:

**Comment by W1nterBr33ze** [comment]
arceus x isnt even updated yet

**Comment by Epikest** [comment]
don't open troll issues or block

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie

**Comment by vbedesu** [comment]
meanie
