### ISSUE TITLE
i cant install plugins (krnl cause im poor)

### ISSUE THREAD

**Issue by UNSPOKENGT** [Infinite-Store/Infinite-Store#31]
when ever i execute the script using krnl, it doesnt allow me to install any plugins, yes, i do click the install button, how ever, nothing seems to work

**Comment by UNSPOKENGT** [comment]
haha im the first one to request an issue

**Comment by UNSPOKENGT** [comment]
oh nvm it worked eventually

**Comment by Epikest** [comment]
bad
