### ISSUE TITLE
crashes when I load the script

### ISSUE THREAD

**Issue by DeceptedPar** [Infinite-Store/Infinite-Store#37]
**Describe the bug**
I load the script and it crashes

**To reproduce**
use synapse X v2.15.3c and load the script
then it'll crash

**Expected behavior**
the game will crash

**Screenshots**
can't get one, the roblox window just closes, no error message

**Desktop (please complete the following information):**
 windows 10
Synapse v2.15.3c (latest version at the time of typing this)

**Additional context**
nothing more to add

**Comment by Toon-arch** [comment]
stfu dumb bi-

**Comment by DeceptedPar** [comment]
now that wasn't very nice
