### ISSUE TITLE
Add theming API

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#39]
### Why?

this is something that has been planned, but never implemented

### What and How?

theme extensions should be `.theme.lua`/`.iy.t`
themes should allow theme developers to modify and distribute their themes freely via infinite store.
this theming api will allow theme creators to modify any aspect of infinite yield and infinite store

### Are there alternatives?

allowing theme creators to make their own "themes" without the use of a theming api, making it harder and less efficient to add and distribute themes

### Checks

- [X] I have started a [thread](https://discord.com/invite/dubhsUGcZe) or [discussion](https://github.com/Infinite-Store/Infinite-Store/discussions/new?category=ideas) regarding my ideas.
- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Toon-arch** [comment]
I confirm this message

**Comment by Epikest** [comment]
lol didn't notice the spam
