### ISSUE TITLE
Migrate databases to separate repository

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#40]
### Why?

this will reduce clutter for plugin creators

### What and How?

create https://github.com/Infinite-Store/Store

### Are there alternatives?

none

### Checks

- [X] I have started a [thread](https://discord.com/invite/dubhsUGcZe) or [discussion](https://github.com/Infinite-Store/Infinite-Store/discussions/new?category=ideas) regarding my ideas.
- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Toon-arch** [comment]
I request perms for the new repo :trollface:

**Comment by Epikest** [comment]
> I request perms for the new repo :trollface:

ok, granted

**Comment by Toon-arch** [comment]
> > I request perms for the new repo :trollface:
> 
> ok, granted

https://www.youtube.com/watch?v=-DhL3YquwAw
