### ISSUE TITLE
TODO: Migrate all raw URLs to CDN

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#43]
example:
https://raw.githubusercontent.com/Infinite-Store/Infinite-Store/main/main.lua would be https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store/main.lua

**Comment by KaizerFox** [comment]
use ctrl f !!!!!!!!!!!!!!

**Comment by Epikest** [comment]
> use ctrl f !!!!!!!!!!!!!!

this is todo because of #40 and #41
