### ISSUE TITLE
TODO: Rename all `*.iy` plugins to `*.plugin.luau`

### ISSUE THREAD

**Issue by Epikest** [Infinite-Store/Infinite-Store#47]
- [x] rename all plugins in the store to `*.plugin.luau` and
- [ ] tell is to save `.luau` plugins as `.iy` files

**Comment by Toon-arch** [comment]
close this smh didnt u just do it!!!

**Comment by Epikest** [comment]
https://github.com/Infinite-Store/Infinite-Store/commit/e6a168c1c67a692f5ae1433abff0995483ae0fe4

**Comment by Epikest** [comment]
not fixed
