### ISSUE TITLE
Infinite Store window not loading

### ISSUE THREAD

**Issue by chancexbox120** [Infinite-Store/Infinite-Store#95]
### Expected behavior

The infinite store window to load, and the infinite store button to work

### Actual behavior

The infinite store window doesn't load, the infinite store button does not work and doesn't load the infinite store window

### Steps to reproduce

install all plugins from infinite store
close roblox
inject with krnl
execute infinite store loadstring
infinite store window does not load and the infinite store button does not work

### Infinite Store version

v5.9

### Checks

- [X] I am __not__ using a mobile device.
- [X] I am __not__ using an outdated version of Infinite Store.
- [x] I asked in [Infinite Store's Discord server](https://discord.com/invite/dubhsUGcZe) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Toon-arch** [comment]
received confirm krnl fixed the issue

**Comment by Toon-arch** [comment]
confirmation*
